import { CHAPTERS } from '../config/levels.js';
import { RANKS } from '../config/game.js';
import { timeLabel, finalScore, rankFor } from '../utils/math.js';
const $=id=>document.getElementById(id);
export class UI {
  constructor(save,audio){this.save=save;this.audio=audio;this.panel=$('panel');this.content=$('panel-content');this.toastTimer=0;this.chapterTimer=0;this.onAction=()=>{};this.panelType='';
    $('close-panel').onclick=()=>this.close();
    this.panel.addEventListener('cancel',e=>{e.preventDefault();this.close();});
    this.panel.addEventListener('click',e=>{if(e.target===this.panel){const r=this.panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.close();}});
    this.content.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)this.onAction(b.dataset.action,b.dataset.value);});
    document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>this.showPanel(b.dataset.panel));
    document.querySelectorAll('.sound-button').forEach(b=>b.onclick=()=>{this.audio.unlock();this.save.set({muted:!this.save.data.muted});this.audio.apply();this.soundLabels();});
    document.querySelectorAll('.fullscreen-button').forEach(b=>b.onclick=()=>this.fullscreen());
    this.content.addEventListener('change',e=>{const k=e.target.dataset.setting;if(!k)return;this.save.set({[k]:e.target.type==='checkbox'?e.target.checked:Number(e.target.value)});this.audio.unlock();this.audio.apply();this.soundLabels();this.motion();});
    this.soundLabels();this.motion();
  }
  show(screen){for(const id of ['menu','game-screen','cinematic'])$(id).classList.toggle('hidden',id!==screen);}
  soundLabels(){document.querySelectorAll('.sound-button').forEach(el=>{el.innerHTML=`${this.save.data.muted?'♫':'♪'}<span>SOUND ${this.save.data.muted?'OFF':'ON'}</span>`;el.setAttribute('aria-label',`Turn sound ${this.save.data.muted?'on':'off'}`);});}
  motion(){document.body.classList.toggle('motion-off',this.save.data.reducedMotion);}
  async fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{this.toast('Fullscreen is unavailable in this browser.');}}
  toast=(text)=>{clearTimeout(this.toastTimer);$('toast').textContent=text;$('toast').classList.add('visible');this.toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),2300);};
  hint=(text)=>{$('objective').querySelector('p').textContent=text;};
  chapter=(level)=>{clearTimeout(this.chapterTimer);const card=$('chapter-card');card.classList.remove('hidden');card.style.animation='none';void card.offsetWidth;card.style.animation='';$('chapter-number').textContent=`CHAPTER ${String(level.index+1).padStart(2,'0')} / 05`;$('chapter-title').textContent=level.name;$('chapter-subtitle').textContent=level.subtitle;$('level-name').textContent=`0${level.index+1} / ${level.name}`;this.hint(level.objective);this.chapterTimer=setTimeout(()=>card.classList.add('hidden'),3000);};
  hud=(game)=>{const s=game.state,b=game.boss;$('energy-value').textContent=Math.ceil(s.energy);$('energy-fill').style.width=s.energy+'%';$('energy-fill').style.background=s.energy<30?'#f28361':'#efb744';$('timer').textContent=timeLabel(s.time);$('timer').parentElement.classList.toggle('danger',s.time<60);$('documents').textContent=String(s.documents).padStart(2,'0');$('score').textContent=String(Math.floor(s.score)).padStart(6,'0');$('phone-fill').style.width=s.phone+'%';$('phone-value').textContent=Math.floor(s.phone)+'%';$('phone-label').textContent=s.slow>0?'DND ACTIVE':s.phone>=99.9?'DO NOT DISTURB · READY':'PHONE RECHARGING';$('wifi').innerHTML=`◉ WI-FI <b>${s.wifi>0?s.wifi.toFixed(0)+'s':'OFFLINE'}</b>`;$('chai').innerHTML=`☕ CHAI <b>${s.chai}${s.chaiBoost>0?' · BOOST':''}</b>`;$('level-progress').innerHTML=CHAPTERS.map((_,i)=>`<span class="${i<=game.level.index?'done':''}" title="Chapter ${i+1}"></span>`).join('');
    $('boss-ui').classList.toggle('hidden',!b||!b.active||b.dead);if(b&&b.active&&!b.dead){$('boss-name').textContent=b.type==='clock'?'THE DEADLINE':'THE PRINTER FROM HELL';$('boss-phase').textContent=b.type==='clock'?`PHASE ${b.phase} / 3`:`${b.hp} / ${b.maxHp}`;$('boss-fill').style.width=b.hp/b.maxHp*100+'%';$('boss-warning').textContent=b.warning;}
    $('trap-ui').classList.toggle('hidden',game.player.trapped<=0);$('trap-fill').style.width=game.player.escape/8*100+'%';
  };
  close(){this.panel.close();this.onAction('close',this.panelType);this.panelType='';}
  open(html,type){this.panelType=type;this.content.innerHTML=html;if(!this.panel.open)this.panel.showModal();}
  showPanel(type){
    if(type==='levels'){this.open(`<h2 class="panel-title">THE LONG WAY THERE.</h2><p class="panel-subtitle">Five chapters. Each one a little less reasonable.<br>Complete a chapter to unlock the next.</p><div class="level-list">${CHAPTERS.map((l,i)=>`<button class="level-option" data-action="level" data-value="${i}" ${i>=this.save.data.unlocked?'disabled':''}><span>0${i+1}</span><div><b>${l.name}</b><small>${l.subtitle}</small></div><em>${i>=this.save.data.unlocked?'LOCKED':'PLAY ↗'}</em></button>`).join('')}</div>`,'levels');}
    if(type==='controls'){const rows=[['Move left / right','A','D','←','→'],['Jump (hold for a higher jump)','SPACE','W','↑'],['Duck / slide under hazards','S','↓'],['Dash · briefly avoid damage','SHIFT'],['Swing the bag','E'],['Phone · 5 seconds of slow motion','F'],['Pause / resume','ESC'],['Escape a quick meeting','SPACE × 8']];this.open(`<h2 class="panel-title">A VERY PARTICULAR<br>SET OF SKILLS.</h2><p class="panel-subtitle">Move with purpose. Jump early. Let the bag do the talking. Touch buttons appear on mobile.</p><div class="control-list">${rows.map(([label,...keys])=>`<div class="control-row"><span>${label}</span><span>${keys.map(k=>`<kbd>${k}</kbd>`).join('')}</span></div>`).join('')}</div><p class="panel-subtitle" style="margin-top:20px">Chai restores 25 energy. Wi-Fi boosts speed for 8 seconds. Documents are worth 500 points.</p>`,'controls');}
    if(type==='score'){const d=this.save.data;this.open(`<h2 class="panel-title">THE OFFICE RECORD.</h2><p class="panel-subtitle">Your best performance on this device.</p><div class="record"><div class="rank-letter">${d.highRank}</div><h3>${RANKS[d.highRank]||'YOUR FIRST MISSION AWAITS'}</h3><div class="record-score">${d.highScore.toLocaleString()} <small>PTS</small></div><small>${d.runs} RUN${d.runs===1?'':'S'} · ${d.unlocked} / 5 CHAPTERS UNLOCKED</small></div>`,'score');}
    if(type==='settings'){const d=this.save.data;this.open(`<h2 class="panel-title">PERSONAL PREFERENCES.</h2><p class="panel-subtitle">Even a mission has settings.</p><label class="setting"><span>Mute all audio<small>Music and sound effects</small></span><input type="checkbox" data-setting="muted" ${d.muted?'checked':''}></label><label class="setting"><span>Background music<small>A soundtrack for questionable decisions</small></span><input type="checkbox" data-setting="music" ${d.music?'checked':''}></label><label class="setting"><span>Volume</span><input aria-label="Volume" type="range" min="0" max="1" step=".05" value="${d.volume}" data-setting="volume"></label><label class="setting"><span>Reduce motion<small>Disable shakes, flashes, and camera zooms</small></span><input type="checkbox" data-setting="reducedMotion" ${d.reducedMotion?'checked':''}></label><div class="panel-actions"><button class="secondary-button" data-action="fullscreen">Toggle fullscreen ⛶</button></div>`,'settings');}
  }
  pause=()=>{this.open('<h2 class="panel-title">TAKE A BREATH, SIR.</h2><p class="panel-subtitle">For once, time is on your side. The meeting timer is paused.</p><button class="play-button" data-action="resume"><strong>BACK TO THE MISSION</strong><span>▶</span></button><div class="panel-actions"><button class="secondary-button" data-action="restart">Restart run</button><button class="secondary-button" data-action="controls">Controls</button><button class="secondary-button" data-action="settings">Settings</button><button class="secondary-button" data-action="home">Main menu</button></div>','pause');};
  result(state,reason){
    const score=finalScore(state);const rank=rankFor({score,damage:state.damage,won:state.won});const best=score>this.save.data.highScore;this.save.record(score,rank);
    const title=state.won?'MISSION FAILED<br>SUCCESSFULLY.':reason==='late'?'YOU ARE LATE.':'SIR NEEDS A CHAI.';
    const line=state.won?'“Meeting cancelled.”<br>Five minutes well spent. Apparently.':reason==='late'?'Meeting rescheduled to tomorrow.':'Your energy ran out. The bag remains undefeated.';
    this.open(`<h2 class="panel-title">${title}</h2><p class="panel-subtitle">${line}</p><div class="record" style="padding:0 0 20px"><div class="rank-letter" style="font-size:80px">${rank}</div><h3>${RANKS[rank]}</h3><div class="record-score">${score.toLocaleString()} <small>PTS ${best?'· NEW BEST':''}</small></div></div><div class="result-grid"><div><small>TIME REMAINING</small><b>${timeLabel(state.time)}</b></div><div><small>DOCUMENTS</small><b>${state.documents}</b></div><div><small>OBSTACLES CLEARED</small><b>${state.defeated}</b></div><div><small>CHAI ACQUIRED</small><b>${state.chai}</b></div></div><div class="panel-actions"><button class="play-button" data-action="restart"><strong>${state.won?'ANOTHER DAY AT WORK':'TRY AGAIN'}</strong><span>↻</span></button><button class="secondary-button" data-action="home">Main menu</button></div>`,'result');
  }
}
